context:
  version: 16.0.6

package:
  name: clang
  version: '{{ version }}'

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version }}.tar.gz
  sha256: 56b2f75fdaa95ad5e477a246d3f0d164964ab066b4619a01836ef08e475ec9d5

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - llvm

about:
  home: https://clang.llvm.org
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: LICENSE.TXT
  summary: clang
  doc_url: https://clang.llvm.org/docs
  dev_url: https://github.com/llvm/llvm-project
